version: "3"

services:
  cms-mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootPass
    volumes:
      - dbdata:/data/db
    networks:
      - cms-app-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootPass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - cms-mongodb
    networks:
      - cms-app-network

networks:
  cms-app-network:
    driver: bridge


volumes:
  dbdata:
  node_modules: 