
name: Deployment
on:
  push:
    branches:
      - account
  pull_request:
    branches:
      - account
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build with Maven
        run: |
            cd ./Account
            mvn package -Dmaven.test.skip
      - name: Build Docker Image
        run: |
            cd ./Account
            docker build -t account -f Dockerfile .
      - name: Generate Deployment Package
        run: |
            cd ./Account
            zip -r deploy.zip * 
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
            aws_access_key: ${{ secrets.ACC_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.ACC_SECRET_ACCESS_KEY }}
            application_name: accountService
            environment_name: Accountservice-env
            version_label: ${{github.SHA}}
            region: ap-southeast-1
            deployment_package: deploy.zip